added cosmos configuartion
DEFRA/ffc-sfd-file-receiver pull request #3
Opened 2024-08-09 13:49 UTC by JungaBunga

https://dev.azure.com/defragovuk/DEFRA-FFC/_boards/board/t/Single%20Front%20Door/Stories?System.Tags=SFD%20Tech&System.AssignedTo=Amirs.Ishmuhametovs%40defra.gov.uk%2CAmirs.Ishmuhametovs%40Defra.onmicrosoft.com&workitem=419234

2024-08-09 14:27 UTC, rtasalem approved these changes

2024-08-09 14:27 UTC, rtasalem commented on app/message/save-to-cosmos.js
> +    console.log('************************', cosmosConfig.filesContainer)
Think we can remove this log now since we only added it in/used it for debugging.

2024-08-09 14:27 UTC, rtasalem commented on appConfig/appConfig.snd4.yaml
> +  value: "https://fcp-sfd-temp-cosmos.documents.azure.com:443/"
You'll be glad to know the files database (`ffc-sfd-customer-receiver-files`) and container (`files-container`) are up and running on our temporary Cosmos instance on SND4! 🤩 You can see it via the [Cosmos DB Data Explorer on the Azure portal](https://portal.azure.com/#@Defra.onmicrosoft.com/resource/subscriptions/da83801b-f7e0-4510-9848-67d87b1009e2/resourceGroups/sndadpinfrg4401-fcp-sfd-temp/providers/Microsoft.DocumentDb/databaseAccounts/fcp-sfd-temp-cosmos/dataExplorer).

2024-08-09 14:29 UTC, rtasalem requested changes
Just one line that I think needs removed.

2024-08-09 14:29 UTC, rtasalem commented on app/message/save-to-cosmos.js
> +    console.log('************************', cosmosConfig.filesContainer)
Think we can remove this log now since we only added it in/used it for debugging.

2024-08-12 07:45 UTC, rtasalem submitted a review, later dismissed

2024-08-13 13:45 UTC, simonnineteen90 commented on docker-compose.yaml
> +      COSMOS_KEY: ${COSMOS_KEY}
Needs cosmos emulator adding in here so it can run on its own without the data service also being ran.

2024-08-13 13:51 UTC, simonnineteen90 commented
Does this currently work in SND4?

2024-08-21 07:33 UTC, simonnineteen90 commented on docker-compose.yaml
> +      COSMOS_KEY: ${COSMOS_KEY}
This can be picked up in a separate tech debt ticket as exploration is needed for best pattern for this and needs actioning across multiple repos.

2024-08-21 07:33 UTC, simonnineteen90 approved these changes

2024-08-21 14:00 UTC, merged